TOPSRCDIR           = ../..
MODULE_NAME         = QuaxeCore

include $(TOPSRCDIR)/swiftbuild/config.mk

SOURCES = \
		Attr.swift \
		CharacterData.swift \
		ChildNode.swift \
		Comment.swift \
		CustomEvent.swift \
		DOMImplementation.swift \
		DOMRange.swift \
		DOMTokenList.swift \
		Document.swift \
		DocumentFragment.swift \
		DocumentType.swift \
		Element.swift \
		Elements.swift \
		Event.swift \
		EventTarget.swift \
		Exception.swift \
		HTMLCollection.swift \
		MutationAlgorithms.swift \
		MutationUtils.swift \
		NamedNodeMap.swift \
		Namespaces.swift \
		Node.swift \
		NodeIterator.swift \
		NodeList.swift \
		NonDocumentTypeChildNode.swift \
		NonElementParentNode.swift \
		OrderedSets.swift \
		ParentNode.swift \
		ProcessingInstruction.swift \
		Text.swift \
		Trees.swift \
		TreeWalker.swift \
		$(NULL)

LIBS= -lQuaxeCoreProtocols

include $(TOPSRCDIR)/swiftbuild/rules.mk
