TOPSRCDIR           = ..

include $(TOPSRCDIR)/swiftbuild/config.mk

MODULE_NAME = QuaxeCore

SOURCES = \
		interfaces/core/DOMString.swift \
		interfaces/core/DOMTimeStamp.swift \
		interfaces/core/pAttr.swift \
		interfaces/core/pCharacterData.swift \
		interfaces/core/pChildNode.swift \
		interfaces/core/pComment.swift \
		interfaces/core/pCustomEvent.swift \
		interfaces/core/pDOMImplementation.swift \
		interfaces/core/pDOMRange.swift \
		interfaces/core/pDOMTokenList.swift \
		interfaces/core/pDocument.swift \
		interfaces/core/pDocumentFragment.swift \
		interfaces/core/pDocumentType.swift \
		interfaces/core/pElement.swift \
		interfaces/core/pElements.swift \
		interfaces/core/pEvent.swift \
		interfaces/core/pEventListener.swift \
		interfaces/core/pEventTarget.swift \
		interfaces/core/pHTMLCollection.swift \
		interfaces/core/pMutationObserver.swift \
		interfaces/core/pMutationRecord.swift \
		interfaces/core/pNamedNodeMap.swift \
		interfaces/core/pNode.swift \
		interfaces/core/pNodeFilter.swift \
		interfaces/core/pNodeIterator.swift \
		interfaces/core/pNodeList.swift \
		interfaces/core/pNonDocumentTypeChildNode.swift \
		interfaces/core/pNonElementParentNode.swift \
		interfaces/core/pParentNode.swift \
		interfaces/core/pProcessingInstruction.swift \
		interfaces/core/pText.swift \
		interfaces/core/pTreeWalker.swift \
		interfaces/core/webidl_types.swift \
		interfaces/events/pEventCreator.swift \
		$(NULL)

SOURCES += \
		core/Attr.swift \
		core/CharacterData.swift \
		core/ChildNode.swift \
		core/Comment.swift \
		core/CustomEvent.swift \
		core/DOMImplementation.swift \
		core/DOMRange.swift \
		core/DOMTokenList.swift \
		core/Document.swift \
		core/DocumentFragment.swift \
		core/DocumentType.swift \
		core/Element.swift \
		core/Elements.swift \
		core/Event.swift \
		core/EventTarget.swift \
		core/Exception.swift \
		core/HTMLCollection.swift \
		core/MutationAlgorithms.swift \
		core/MutationUtils.swift \
		core/NamedNodeMap.swift \
		core/Namespaces.swift \
		core/Node.swift \
		core/NodeIterator.swift \
		core/NodeList.swift \
		core/NonDocumentTypeChildNode.swift \
		core/NonElementParentNode.swift \
		core/OrderedSets.swift \
		core/ParentNode.swift \
		core/ProcessingInstruction.swift \
		core/Text.swift \
		core/TreeWalker.swift \
		core/Trees.swift \
		$(NULL)

SOURCES += \
		events/EventCreator.swift \
		$(NULL)

include $(TOPSRCDIR)/swiftbuild/rules.mk
