TOPSRCDIR           = ..

include $(TOPSRCDIR)/swiftbuild/config.mk

MODULE_NAME = Quaxe

SOURCES = \
		core/protocols/DOMString.swift \
		core/protocols/DOMTimeStamp.swift \
		core/protocols/pAttr.swift \
		core/protocols/pCharacterData.swift \
		core/protocols/pChildNode.swift \
		core/protocols/pComment.swift \
		core/protocols/pCustomEvent.swift \
		core/protocols/pDOMImplementation.swift \
		core/protocols/pDOMRange.swift \
		core/protocols/pDOMTokenList.swift \
		core/protocols/pDocument.swift \
		core/protocols/pDocumentFragment.swift \
		core/protocols/pDocumentType.swift \
		core/protocols/pElement.swift \
		core/protocols/pElements.swift \
		core/protocols/pEvent.swift \
		core/protocols/pEventListener.swift \
		core/protocols/pEventTarget.swift \
		core/protocols/pHTMLCollection.swift \
		core/protocols/pMutationObserver.swift \
		core/protocols/pMutationRecord.swift \
		core/protocols/pNamedNodeMap.swift \
		core/protocols/pNode.swift \
		core/protocols/pNodeFilter.swift \
		core/protocols/pNodeIterator.swift \
		core/protocols/pNodeList.swift \
		core/protocols/pNonDocumentTypeChildNode.swift \
		core/protocols/pNonElementParentNode.swift \
		core/protocols/pParentNode.swift \
		core/protocols/pProcessingInstruction.swift \
		core/protocols/pText.swift \
		core/protocols/pTreeWalker.swift \
		core/protocols/webidl_types.swift \
		events/protocols/pEventCreator.swift \
		$(NULL)

SOURCES += \
		core/Attr.swift \
		core/CharacterData.swift \
		core/ChildNode.swift \
		core/Comment.swift \
		core/CustomEvent.swift \
		core/DOMImplementation.swift \
		core/DOMRange.swift \
		core/DOMTokenList.swift \
		core/Document.swift \
		core/DocumentFragment.swift \
		core/DocumentType.swift \
		core/Element.swift \
		core/Elements.swift \
		core/Event.swift \
		core/EventTarget.swift \
		core/Exception.swift \
		core/HTMLCollection.swift \
		core/MutationAlgorithms.swift \
		core/MutationUtils.swift \
		core/NamedNodeMap.swift \
		core/Namespaces.swift \
		core/Node.swift \
		core/NodeIterator.swift \
		core/NodeList.swift \
		core/NonDocumentTypeChildNode.swift \
		core/NonElementParentNode.swift \
		core/OrderedSets.swift \
		core/ParentNode.swift \
		core/ProcessingInstruction.swift \
		core/Text.swift \
		core/TreeWalker.swift \
		core/Trees.swift \
		core/XMLParser.swift \
		$(NULL)

SOURCES += \
		events/EventCreator.swift \
		$(NULL)

include $(TOPSRCDIR)/swiftbuild/rules.mk
