TOPSRCDIR           = ..

include $(TOPSRCDIR)/swiftbuild/config.mk

MODULE_NAME = Quaxe

SOURCES = \
		protocols/core/DOMString.swift \
		protocols/core/DOMTimeStamp.swift \
		protocols/core/pAttr.swift \
		protocols/core/pCharacterData.swift \
		protocols/core/pChildNode.swift \
		protocols/core/pComment.swift \
		protocols/core/pCustomEvent.swift \
		protocols/core/pDOMImplementation.swift \
		protocols/core/pDOMRange.swift \
		protocols/core/pDOMTokenList.swift \
		protocols/core/pDocument.swift \
		protocols/core/pDocumentFragment.swift \
		protocols/core/pDocumentType.swift \
		protocols/core/pElement.swift \
		protocols/core/pElements.swift \
		protocols/core/pEvent.swift \
		protocols/core/pEventListener.swift \
		protocols/core/pEventTarget.swift \
		protocols/core/pHTMLCollection.swift \
		protocols/core/pMutationObserver.swift \
		protocols/core/pMutationRecord.swift \
		protocols/core/pNamedNodeMap.swift \
		protocols/core/pNode.swift \
		protocols/core/pNodeFilter.swift \
		protocols/core/pNodeIterator.swift \
		protocols/core/pNodeList.swift \
		protocols/core/pNonDocumentTypeChildNode.swift \
		protocols/core/pNonElementParentNode.swift \
		protocols/core/pParentNode.swift \
		protocols/core/pProcessingInstruction.swift \
		protocols/core/pText.swift \
		protocols/core/pTreeWalker.swift \
		protocols/core/webidl_types.swift \
		$(NULL)

SOURCES += \
		protocols/style/pMediaList.swift \
		protocols/style/pStyleSheet.swift \
		protocols/style/pStyleSheetList.swift \
		protocols/style/pLinkStyle.swift \
		protocols/style/pDocumentStyle.swift \
		$(NULL)

SOURCES += \
		protocols/css/pCSSCharsetRule.swift \
		protocols/css/pCSSFontFaceRule.swift \
		protocols/css/pCSSImportRule.swift \
		protocols/css/pCSSMediaRule.swift \
		protocols/css/pCSSPageRule.swift \
		protocols/css/pCSSRule.swift \
		protocols/css/pCSSUnknownRule.swift \
		protocols/css/pCSSRuleList.swift \
		protocols/css/pCSSStyleDeclaration.swift \
		protocols/css/pCSSStyleRule.swift \
		protocols/css/pCSSStyleSheet.swift \
		protocols/css/pCSSValue.swift \
		protocols/css/pElementCSSInlineStyle.swift \
		protocols/css/pViewCSS.swift \
		$(NULL)

SOURCES += \
		protocols/events/pEventCreator.swift \
		$(NULL)

SOURCES += \
		core/Attr.swift \
		core/CharacterData.swift \
		core/ChildNode.swift \
		core/Comment.swift \
		core/CustomEvent.swift \
		core/DOMImplementation.swift \
		core/DOMRange.swift \
		core/DOMTokenList.swift \
		core/Document.swift \
		core/DocumentFragment.swift \
		core/DocumentType.swift \
		core/Element.swift \
		core/Elements.swift \
		core/Event.swift \
		core/EventTarget.swift \
		core/Exception.swift \
		core/HTMLCollection.swift \
		core/MutationAlgorithms.swift \
		core/MutationUtils.swift \
		core/NamedNodeMap.swift \
		core/Namespaces.swift \
		core/Node.swift \
		core/NodeIterator.swift \
		core/NodeList.swift \
		core/NonDocumentTypeChildNode.swift \
		core/NonElementParentNode.swift \
		core/OrderedSets.swift \
		core/ParentNode.swift \
		core/ProcessingInstruction.swift \
		core/Text.swift \
		core/TreeWalker.swift \
		core/Trees.swift \
		core/XMLParser.swift \
		$(NULL)

SOURCES += \
		style/StyleSheet.swift \
		style/StyleSheetList.swift \
		style/MediaList.swift \
		$(NULL)

SOURCES += \
		events/EventCreator.swift \
		$(NULL)

include $(TOPSRCDIR)/swiftbuild/rules.mk
