TOPSRCDIR           = ../..
MODULE_NAME         = QuaxeHtmlOm

SOURCES = \
		DOMException.swift \
		DOMTimeStamp.swift \
		Event.swift \
		EventTarget.swift \
		$(NULL)

include $(TOPSRCDIR)/config/rules.mk
