TOPSRCDIR           = ..
MODULE_NAME         = QuaxeCore

include $(TOPSRCDIR)/swiftbuild/config.mk

LIBS = -lQuaxeUtils

SOURCES = \
		protocols/pAttr.swift \
		protocols/pCharacterData.swift \
		protocols/pChildNode.swift \
		protocols/pComment.swift \
		protocols/pCustomEvent.swift \
		protocols/pDocument.swift \
		protocols/pDocumentFragment.swift \
		protocols/pDocumentType.swift \
		protocols/pDOMImplementation.swift \
		protocols/pDOMRange.swift \
		protocols/DOMString.swift \
		protocols/DOMTimeStamp.swift \
		protocols/pDOMTokenList.swift \
		protocols/pElement.swift \
		protocols/pElements.swift \
		protocols/pEvent.swift \
		protocols/pEventListener.swift \
		protocols/pEventTarget.swift \
		protocols/pHTMLCollection.swift \
		protocols/pMutationObserver.swift \
		protocols/pMutationRecord.swift \
		protocols/pNamedNodeMap.swift \
		protocols/pNode.swift \
		protocols/pNodeFilter.swift \
		protocols/pNodeIterator.swift \
		protocols/pNonDocumentTypeChildNode.swift \
		protocols/pNonElementParentNode.swift \
		protocols/pNodeList.swift \
		protocols/pParentNode.swift \
		protocols/pProcessingInstruction.swift \
		protocols/pText.swift \
		protocols/pTreeWalker.swift \
		protocols/webidl_types.swift \
		AtomicTreeActions.swift \
		Attr.swift \
		CharacterData.swift \
		ChildNode.swift \
		Comment.swift \
		CustomEvent.swift \
		DOMImplementation.swift \
		DOMRange.swift \
		DOMTokenList.swift \
		Document.swift \
		DocumentFragment.swift \
		DocumentType.swift \
		Element.swift \
		Elements.swift \
		Event.swift \
		EventTarget.swift \
		Exception.swift \
		HTMLCollection.swift \
		MutationAlgorithms.swift \
		MutationUtils.swift \
		NamedNodeMap.swift \
		Namespaces.swift \
		Node.swift \
		NodeIterator.swift \
		NodeList.swift \
		NonDocumentTypeChildNode.swift \
		NonElementParentNode.swift \
		ParentNode.swift \
		ProcessingInstruction.swift \
		Text.swift \
		TreeWalker.swift \
		$(NULL)

include $(TOPSRCDIR)/swiftbuild/rules.mk
