TOPSRCDIR           = ..
MODULE_NAME         = QuaxeCore

SOURCES = \
		CustomEvent.swift \
		Document.swift \
		DocumentFragment.swift \
		DOMException.swift \
		DOMTimeStamp.swift \
		Element.swift \
		Event.swift \
		EventTarget.swift \
		NonElementParentNode.swift \
		NonElementParentNodeImpl.swift \
		$(NULL)

include $(TOPSRCDIR)/config/rules.mk
