TOPSRCDIR           = ../../..
MODULE_NAME         = QuaxeCoreProtocols

include $(TOPSRCDIR)/swiftbuild/config.mk

SOURCES = \
		pAttr.swift \
		pCharacterData.swift \
		pChildNode.swift \
		pComment.swift \
		pCustomEvent.swift \
		pDocument.swift \
		pDocumentFragment.swift \
		pDocumentType.swift \
		pDOMImplementation.swift \
		pDOMRange.swift \
		DOMString.swift \
		DOMTimeStamp.swift \
		pDOMTokenList.swift \
		pElement.swift \
		pElements.swift \
		pEvent.swift \
		pEventListener.swift \
		pEventTarget.swift \
		pHTMLCollection.swift \
		pMutationObserver.swift \
		pMutationRecord.swift \
		pNamedNodeMap.swift \
		pNode.swift \
		pNodeFilter.swift \
		pNodeIterator.swift \
		pNonDocumentTypeChildNode.swift \
		pNonElementParentNode.swift \
		pNodeList.swift \
		pParentNode.swift \
		pProcessingInstruction.swift \
		pText.swift \
		pTreeWalker.swift \
		webidl_types.swift \
		$(NULL)

include $(TOPSRCDIR)/swiftbuild/rules.mk
