TOPSRCDIR           = ..

include $(TOPSRCDIR)/swiftbuild/config.mk

MODULE_NAME = QuaxeParser

SOURCES += \
    css/CSSToken.swift \
    css/CSSScanner.swift \
		css/CSSParser.swift \
		$(NULL)

include $(TOPSRCDIR)/swiftbuild/rules.mk
