TOPSRCDIR           = ..
MODULE_NAME         = QuaxeUtils

include $(TOPSRCDIR)/swiftbuild/config.mk

SOURCES = \
		Operators.swift \
		Combinators.swift \
		Either.swift \
		Regexp.swift \
		String.swift \
		Weak.swift \
		$(NULL)

include $(TOPSRCDIR)/swiftbuild/rules.mk
