TOPSRCDIR           = ..
MODULE_NAME         = QuaxeUtils

include $(TOPSRCDIR)/swiftbuild/config.mk

SOURCES = \
		Combinators.swift \
		Either.swift \
		$(NULL)

include $(TOPSRCDIR)/swiftbuild/rules.mk
