TOPSRCDIR           = ../..
MODULE_NAME         = QuaxeCoreProtocols

include $(TOPSRCDIR)/swiftbuild/config.mk

SOURCES = \
		Attr.swift \
		CharacterData.swift \
		ChildNode.swift \
		Comment.swift \
		CustomEvent.swift \
		Document.swift \
		DocumentFragment.swift \
		DocumentType.swift \
		DOMImplementation.swift \
		DOMRange.swift \
		DOMString.swift \
		DOMTimeStamp.swift \
		DOMTokenList.swift \
		Element.swift \
		Elements.swift \
		Event.swift \
		EventListener.swift \
		EventTarget.swift \
		HTMLCollection.swift \
		MutationObserver.swift \
		MutationRecord.swift \
		NamedNodeMap.swift \
		Node.swift \
		NodeFilter.swift \
		NodeIterator.swift \
		NonDocumentTypeChildNode.swift \
		NonElementParentNode.swift \
		NodeList.swift \
		ParentNode.swift \
		ProcessingInstruction.swift \
		Text.swift \
		TreeWalker.swift \
		webidl_types.swift \
		$(NULL)

include $(TOPSRCDIR)/swiftbuild/rules.mk
